### ISSUE TITLE
ItemDialer.func_94581

### ISSUE THREAD

**Issue by ilvinc3nt** [XFactHD/RFUtilities#1]
updating to new version (v. 0.3) it crashes.

This is the log:

java.lang.ArrayIndexOutOfBoundsException: 1
    at XFactHD.rfutilities.common.items.ItemDialer.func_94581_a(ItemDialer.java:89)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:481)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:97)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:547)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by XFactHD** [comment]
I overlooked something, will provide a fix in a few minutes.
