### ISSUE TITLE
Placing creative cell -> diode -> switch [off] -> resistor [0 rf/t] causes RFU to create consloe spam and crash with StackOverflow

### ISSUE THREAD

**Issue by MineWitherMC** [XFactHD/RFUtilities#3]
Warning, LARGE crashreport...
http://codepad.org/itbmolUI

**Comment by XFactHD** [comment]
What do you mean with spamming? What does it spam?

**Comment by MineWitherMC** [comment]
at XFactHD.rfutilities.common.blocks.tileEntity.TileEntitySwitch.receiveNS(TileEntitySwitch.java:60)
    at XFactHD.rfutilities.common.blocks.tileEntity.TileEntitySwitch.receiveEnergy(TileEntitySwitch.java:45)
    at XFactHD.rfutilities.common.blocks.tileEntity.TileEntityResistor.receiveNS(TileEntityResistor.java:61)
    at XFactHD.rfutilities.common.blocks.tileEntity.TileEntityResistor.receiveEnergy(TileEntityResistor.java:51)
As I can see in code, switch and resistor give energy each other and cause StackOverflow.

**Comment by XFactHD** [comment]
Yep, that's most likely what is going on, I'll look into it as soon as possible.
Just for clarification, does it spam those lines already before the game crashes?

**Comment by MineWitherMC** [comment]
Yep as this crash is server-side. Sorry for not answering for 18 hours, I couldn't.

**Comment by XFactHD** [comment]
No problem, I just wanted to know it, it doesn't change anything for the fix.

**Comment by XFactHD** [comment]
In my tests, this crash did only happen after I activated the switch.

**Comment by XFactHD** [comment]
Fixed, new file is on curse.
